// src/enums/transaction-types.enum.ts

/**
 * All transaction types supported by the accounting system
 * Matches the trigger functions and database schema
 */
export enum TransactionType {
    // ========== STUDENT FEES (MSchool) ==========
    STUDENT_FEE_PAYMENT = 'STUDENT_FEE_PAYMENT',
    STUDENT_FEE_ADVANCE = 'STUDENT_FEE_ADVANCE',
    STUDENT_FEE_REFUND = 'STUDENT_FEE_REFUND',
    STUDENT_FEE_DISCOUNT = 'STUDENT_FEE_DISCOUNT',
    STUDENT_FEE_WAIVER = 'STUDENT_FEE_WAIVER',
    STUDENT_LATE_FEE = 'STUDENT_LATE_FEE',
    STUDENT_FINE = 'STUDENT_FINE',
    STUDENT_SECURITY_DEPOSIT = 'STUDENT_SECURITY_DEPOSIT',

    // ========== TRANSPORT (MSchool) ==========
    TRANSPORT_FEE = 'TRANSPORT_FEE',
    TRANSPORT_ADVANCE = 'TRANSPORT_ADVANCE',
    TRANSPORT_REFUND = 'TRANSPORT_REFUND',
    TRANSPORT_DISCOUNT = 'TRANSPORT_DISCOUNT',

    // ========== SALARY & STAFF (MSchool/MHR) ==========
    SALARY_PAYMENT = 'SALARY_PAYMENT',
    ADVANCE_SALARY = 'ADVANCE_SALARY',
    BONUS_PAYMENT = 'BONUS_PAYMENT',
    INCENTIVE_PAYMENT = 'INCENTIVE_PAYMENT',
    DRIVER_INCENTIVE = 'DRIVER_INCENTIVE',
    ATTENDER_INCENTIVE = 'ATTENDER_INCENTIVE',
    TEACHER_INCENTIVE = 'TEACHER_INCENTIVE',
    STAFF_LOAN = 'STAFF_LOAN',
    LOAN_REPAYMENT = 'LOAN_REPAYMENT',
    EMPLOYEE_ADVANCE = 'EMPLOYEE_ADVANCE',
    EMPLOYEE_EXPENSE = 'EMPLOYEE_EXPENSE',

    // ========== EXPENSES (All Apps) ==========
    OPERATING_EXPENSE = 'OPERATING_EXPENSE',
    CAPITAL_EXPENSE = 'CAPITAL_EXPENSE',
    UTILITY_EXPENSE = 'UTILITY_EXPENSE',
    MAINTENANCE_EXPENSE = 'MAINTENANCE_EXPENSE',
    OFFICE_EXPENSE = 'OFFICE_EXPENSE',
    MARKETING_EXPENSE = 'MARKETING_EXPENSE',
    TRAVEL_EXPENSE = 'TRAVEL_EXPENSE',
    STATIONERY_EXPENSE = 'STATIONERY_EXPENSE',
    PRINTING_EXPENSE = 'PRINTING_EXPENSE',
    INTERNET_EXPENSE = 'INTERNET_EXPENSE',
    RENT_EXPENSE = 'RENT_EXPENSE',
    ELECTRICITY_EXPENSE = 'ELECTRICITY_EXPENSE',
    WATER_EXPENSE = 'WATER_EXPENSE',

    // ========== E-COMMERCE (MSuite/MPOS) ==========
    SALES_INVOICE = 'SALES_INVOICE',
    SALES_RETURN = 'SALES_RETURN',
    PURCHASE_INVOICE = 'PURCHASE_INVOICE',
    PURCHASE_RETURN = 'PURCHASE_RETURN',
    AFFILIATE_PAYMENT = 'AFFILIATE_PAYMENT',
    COMMISSION_PAYMENT = 'COMMISSION_PAYMENT',
    VENDOR_PAYMENT = 'VENDOR_PAYMENT',
    CUSTOMER_REFUND = 'CUSTOMER_REFUND',
    VENDOR_REFUND = 'VENDOR_REFUND',

    // ========== TAX PAYMENTS ==========
    GST_PAYMENT = 'GST_PAYMENT',
    TDS_PAYMENT = 'TDS_PAYMENT',
    TAX_REFUND = 'TAX_REFUND',
    GST_FILING_FEE = 'GST_FILING_FEE',
    INCOME_TAX_PAYMENT = 'INCOME_TAX_PAYMENT',
    PROFESSIONAL_TAX = 'PROFESSIONAL_TAX',

    // ========== BANK & CASH ==========
    BANK_DEPOSIT = 'BANK_DEPOSIT',
    BANK_WITHDRAWAL = 'BANK_WITHDRAWAL',
    CASH_DEPOSIT = 'CASH_DEPOSIT',
    CASH_WITHDRAWAL = 'CASH_WITHDRAWAL',
    BANK_TRANSFER = 'BANK_TRANSFER',
    FD_CREATION = 'FD_CREATION',
    FD_MATURITY = 'FD_MATURITY',

    // ========== INVESTMENTS ==========
    INVESTMENT_PURCHASE = 'INVESTMENT_PURCHASE',
    INVESTMENT_SALE = 'INVESTMENT_SALE',
    DIVIDEND_INCOME = 'DIVIDEND_INCOME',
    INTEREST_INCOME = 'INTEREST_INCOME',

    // ========== ACCOUNTING VOUCHERS ==========
    JOURNAL_VOUCHER = 'JOURNAL_VOUCHER',
    CONTRA_VOUCHER = 'CONTRA_VOUCHER',
    RECEIPT_VOUCHER = 'RECEIPT_VOUCHER',
    PAYMENT_VOUCHER = 'PAYMENT_VOUCHER',
    DEBIT_NOTE = 'DEBIT_NOTE',
    CREDIT_NOTE = 'CREDIT_NOTE',

    // ========== MISCELLANEOUS ==========
    DONATION_RECEIPT = 'DONATION_RECEIPT',
    GRANT_RECEIVED = 'GRANT_RECEIVED',
    PENALTY_INCOME = 'PENALTY_INCOME',
    FINE_INCOME = 'FINE_INCOME',
    DISCOUNT_ALLOWED = 'DISCOUNT_ALLOWED',
    DISCOUNT_RECEIVED = 'DISCOUNT_RECEIVED',
    ROUND_OFF = 'ROUND_OFF'
}

/**
 * Transaction status
 */
export enum TransactionStatus {
    DRAFT = 'DRAFT',
    PENDING = 'PENDING',
    POSTED = 'POSTED',
    CANCELLED = 'CANCELLED',
    REVERSED = 'REVERSED',
    RECONCILED = 'RECONCILED'
}

/**
 * Payment methods
 */
export enum PaymentMethod {
    CASH = 'CASH',
    CHEQUE = 'CHEQUE',
    ONLINE_TRANSFER = 'ONLINE_TRANSFER',
    UPI = 'UPI',
    CREDIT_CARD = 'CREDIT_CARD',
    DEBIT_CARD = 'DEBIT_CARD',
    MOBILE_WALLET = 'MOBILE_WALLET',
    BANK_TRANSFER = 'BANK_TRANSFER',
    DEMAND_DRAFT = 'DEMAND_DRAFT',
    NEFT = 'NEFT',
    RTGS = 'RTGS',
    IMPS = 'IMPS'
}